server:
  port: 7500
spring:
    datasource:
      url: jdbc:mysql://192.168.10.134:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      url: jdbc:mysql://10.100.2.30:3306/xcloud_user?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      db-name: demo
xcloud:
  generate: #开发工具
    project-location: F:/eureka-cluster/provider
    developer: wangjiliang
    table-prefix: t_

security:
  basic:
    enabled: false